version: "3"

services:

  nuxt:
    build: .
    container_name: cpa-front
    restart: always
    ports:
      - "6000:6000"
    expose:
      - "6000"
    command:
      "npm run start"
    environment:
      VIRTUAL_HOST: cpa.bcc.anapolis.ifg.edu.br
      HTTP_PORT: 6000
      LETSENCRYPT_HOST: cpa.bcc.anapolis.ifg.edu.br
      LETSENCRYPT_EMAIL: "devbaraus@gmail.com"
    networks:
      nginx-proxy:

networks:
  external:
    name: nginx-proxy
